enableRobotsTXT = true
enableGitInfo = true

[params.footer]
copyright = "No"

[[menu.main]]
name = "About"
url = "/about/index.html"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts/index.html"
weight = 2